[package]
name = "ink-fmt"
version = "0.1.0"
edition = "2021"

[dependencies]
tree-sitter = "0.22"
tree-sitter-ink = { path = "../tree-sitter-ink/", version = '24.6.18'}

[dev-dependencies]
derive_builder = "0.20.0"
markdown = "1.0.0-alpha.17"
pretty_assertions = "1.4.0"

[build-dependencies]
cc="*"
