[package]
name = "ink-tool"
description = "Toolset for Inkle's Ink language"
keywords = ["ink", "formatter", "language-server"]
categories = ["command-line-utilities", "development-tools", "game-development"]
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.18", features = ["derive"] }
itertools = "0.13.0"
jsonrpc = "0.18.0"
line-index = "0.1.1"
lsp-server = "0.7.7"
lsp-types = "0.97.0"
notify = "6.1.1"
serde = "1.0.210"
serde_json = "1.0.128"
thiserror = "1.0.64"
tree-sitter = "0.23"
tree-sitter-ink = { path = "../tree-sitter-ink/", version = '24.6.18'}
walkdir = "2.5.0"

[dev-dependencies]
pretty_assertions = "1.4.0"
quickcheck = "1.0.3"
strum = { version = "0.26.3", features = ["derive"] }
test-case = "3.3.1"

[build-dependencies]
cc="*"
derive_builder = "0.20.0"
markdown = "1.0.0-alpha.17"
tree-sitter-ink = { path = "../tree-sitter-ink/", version = '24.6.18'}

[dependencies.type-sitter-lib]
version = "^0"
# path = "../type-sitter/type-sitter-lib"
# git = "https://github.com/wldmr/type-sitter.git"
git = "https://github.com/jakobeha/type-sitter.git"
# branch = "main"

[build-dependencies.type-sitter-gen]
version = "^0"
# path = "../type-sitter/type-sitter-gen"
# git = "https://github.com/wldmr/type-sitter.git"
git = "https://github.com/jakobeha/type-sitter.git"
# branch = "main"

[profile.release]
strip = true
lto = "thin"
codegen-units = 1
