[package]
name = "ink-fmt"
version = "0.1.0"
edition = "2021"

[dependencies]
tree-sitter = "0.22"
tree-sitter-ink = { path = "../tree-sitter-ink/", version = '24.6.18'}

[dependencies.type-sitter-lib]
git = "https://github.com/wldmr/type-sitter.git"
branch = "3-replacement-names-clash"

[dev-dependencies]
pretty_assertions = "1.4.0"

[build-dependencies]
cc="*"
derive_builder = "0.20.0"
markdown = "1.0.0-alpha.17"
rust-format = "0.3.4"

[build-dependencies.type-sitter-gen]
git = "https://github.com/wldmr/type-sitter.git"
branch = "3-replacement-names-clash"
